### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.randint(1, 31, size=10)
media = np.mean(arr)
desvio_padrao = np.std(arr)

print('array com 10 números, ', arr)
print('media gerada, ', media)
print('desvio padrao gerado, ', desvio_padrao)

array com 10 números,  [14 18  6  2  6 12 18 30  8  4]
media gerada,  11.8
desvio padrao gerado,  8.072174428244226


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)

arr_menor = np.where(arr <= 0.5)

arr_raiz_quadrada = np.sqrt(arr[arr_menor])

print('array original, ', arr)
print('os valores selecionados foram ', arr[arr_menor])
print('raiz quadrada dos valores menores ou iguais a 0,5 ', arr_raiz_quadrada)

array original,  [0.52521647 0.17052247 0.16141757 0.22011569 0.26359016 0.67156658
 0.03326673 0.12913759 0.83715919 0.80070793]
os valores selecionados foram  [0.17052247 0.16141757 0.22011569 0.26359016 0.03326673 0.12913759]
raiz quadrada dos valores menores ou iguais a 0,5  [0.41294366 0.40176805 0.46916489 0.51341033 0.18239169 0.35935719]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)

print("Matriz 3D:\n", matriz)

for i in range(matriz.shape[0]):
    print("Máximo de cada linha da matriz 2D", i, ":\n", np.amax(matriz[i, :, :], axis=1))

Matriz 3D:
 [[[0.46461025 0.18025968 0.55653913]
  [0.7993486  0.65598297 0.92945952]
  [0.70386075 0.93762439 0.65358895]]

 [[0.33569357 0.28187617 0.17997463]
  [0.109189   0.00350664 0.24411439]
  [0.44854572 0.98865127 0.67643404]]

 [[0.93023861 0.53373951 0.31327797]
  [0.6174354  0.45589182 0.63416523]
  [0.58172916 0.83209162 0.72928861]]]
Máximo de cada linha da matriz 2D 0 :
 [0.55653913 0.92945952 0.93762439]
Máximo de cada linha da matriz 2D 1 :
 [0.33569357 0.24411439 0.98865127]
Máximo de cada linha da matriz 2D 2 :
 [0.93023861 0.63416523 0.83209162]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)
print("Matriz original:\n", matriz)

matriz_sub = matriz - np.mean(matriz, axis=1, keepdims=True)

print("Matriz com a média de cada linha subtraída:\n", matriz_sub)
  

Matriz original:
 [[0.72308403 0.26423946 0.65900897 0.73196902 0.49031705]
 [0.91680187 0.00184579 0.18035556 0.50071607 0.55927652]
 [0.50289917 0.15505778 0.71020302 0.04292766 0.18284078]
 [0.62558394 0.71924366 0.17960491 0.29977505 0.78978451]
 [0.35787041 0.69985273 0.95876109 0.13041024 0.75393922]]
Matriz com a média de cada linha subtraída:
 [[ 0.14936032 -0.30948424  0.08528526  0.15824531 -0.08340665]
 [ 0.48500271 -0.42995337 -0.2514436   0.06891691  0.12747736]
 [ 0.18411349 -0.1637279   0.39141734 -0.27585802 -0.1359449 ]
 [ 0.10278553  0.19644524 -0.3431935  -0.22302337  0.2669861 ]
 [-0.22229633  0.11968599  0.37859435 -0.44975649  0.17377249]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)

diagonal_principal = np.diag(matriz)
diagonal_secundaria = np.diag(np.fliplr(matriz))
media_diagonal = np.mean([diagonal_principal, diagonal_secundaria])
std_diagonal = np.std([diagonal_principal, diagonal_secundaria])

# Exibir os resultados
print("Matriz:\n", matriz)
print("Diagonal principal:\n", diagonal_principal)
print("Diagonal secundária:\n", diagonal_secundaria)
print("Média das diagonais:", media_diagonal)
print("Desvio padrão das diagonais:", std_diagonal)


Matriz:
 [[0.89211566 0.05765036 0.88889211 0.67833661]
 [0.24710346 0.71662392 0.90487286 0.62091583]
 [0.53098465 0.0668204  0.75532793 0.85665348]
 [0.30330236 0.36993854 0.42178848 0.12290733]]
Diagonal principal:
 [0.89211566 0.71662392 0.75532793 0.12290733]
Diagonal secundária:
 [0.67833661 0.90487286 0.0668204  0.30330236]
Média das diagonais: 0.5550383843100123
Desvio padrão das diagonais: 0.3173914304924737
